### ISSUE TITLE
Bugged toffee quary texture in toyland

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#64] opened 2023-11-18 12:06 UTC
![Screenshot_2023-11-18-14-03-47-458_org openttd sdl](https://github.com/zephyris/opengfx2/assets/145707519/a71f063b-681a-437d-9558-a56e14d2ce8b)

**Comment by zephyris** [comment] 2023-11-19 13:01
Presumably duplicate of #30

**Closed by zephyris** 2023-11-19 13:01 UTC
